{
 "title": "IBM DB2 overview",
 "tags": [ "ibm-db2-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ibm_db2_application_active{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(ibm_db2_application_active{job=~\"$job\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(ibm_db2_application_active{job=~\"$job\",cluster=~\"$cluster\"}, instance)"
   },
   {
    "name": "database_name",
    "label": "Database",
    "query": "label_values(ibm_db2_application_active{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}, database_name)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Up status",
   "type": "stat",
   "description": "Whether the agent integration is up for this database.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ibm_db2_up{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",database_name=~\"$database_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "description": "The amount of active connections to the database.",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibm_db2_application_active{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",database_name=~\"$database_name\"}",
     "legendFormat": "{{database_name}}"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 7 } },
  {
   "title": "Row operations",
   "type": "timeseries",
   "description": "The number of row operations that are being performed on the database.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(ibm_db2_row_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",database_name=~\"$database_name\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{database_name}} - {{row_state}}"
    }
   ]
  },
  {
   "title": "Bufferpool hit ratio",
   "type": "timeseries",
   "description": "The percentage of time that the database manager did not need to load a page from disk to service a page request.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ibm_db2_bufferpool_hit_ratio{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",database_name=~\"$database_name\"}",
     "legendFormat": "{{database_name}} - {{bufferpool_name}}"
    }
   ]
  },
  { "title": "Tablespace", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 14 } },
  {
   "title": "Tablespace usage",
   "type": "timeseries",
   "description": "The size and usage of table spaces.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ibm_db2_tablespace_usage{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",database_name=~\"$database_name\", tablespace_type=\"used\"}",
     "legendFormat": "{{database_name}} - {{tablespace_name}}"
    }
   ]
  },
  { "title": "Locks", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 21 } },
  {
   "title": "Average lock wait time",
   "type": "timeseries",
   "description": "The average wait time for a database while acquiring locks.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ibm_db2_lock_wait_time{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",database_name=~\"$database_name\"}",
     "legendFormat": "{{database_name}}"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "description": "The number of deadlocks occurring on the database.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(ibm_db2_deadlock_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",database_name=~\"$database_name\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{database_name}}"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "description": "The number of locks active and waiting in use in the database.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibm_db2_lock_usage{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",database_name=~\"$database_name\"}",
     "legendFormat": "{{database_name}} - {{lock_state}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 28 } },
  {
   "title": "Log storage usage",
   "type": "stat",
   "description": "The percentage of allocated storage being used by the IBM DB2 instance.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(ibm_db2_log_usage{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",database_name=~\"$database_name\", log_usage_type=\"used\"}) by (instance, job, database_name) / clamp_min(sum(ibm_db2_log_usage{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",database_name=~\"$database_name\", log_usage_type=\"available\"}) by (instance, job, database_name), 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log operations",
   "type": "timeseries",
   "description": "The number of log pages read and written to by the logger.",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(ibm_db2_log_operations_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",database_name=~\"$database_name\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{database_name}} - {{log_member}} - {{log_operation_type}}"
    }
   ]
  }
 ]
}